---
- name: install | ensure mysql group is set
  group:
    name: '{{ percona_mysql_user.name }}'
    gid: '{{ percona_mysql_user.gid }}'
    system: true

- name: install | ensure mysql user is set
  user:
    name: '{{ percona_mysql_user.name }}'
    uid: '{{ percona_mysql_user.uid }}'
    system: true
    group: '{{ percona_mysql_user.name }}'
    comment: '{{ percona_mysql_user.comment }}'
    home: '{{ percona_mysql_user.home }}'
    create_home: false
    shell: '{{ percona_mysql_user.shell }}'

- name: install | ensure mysql and certs folder exists
  file:
    state: directory
    path: "{{ item }}"
    owner: '{{ percona_mysql_user.name }}'
    group: '{{ percona_mysql_user.name }}'
    mode: '0755'
  loop:
    - /etc/mysql
    - /etc/mysql/certs

- name: install | percona when not installed
  block:

    - name: install | dependencies
      dnf:
        name: "{{ percona_package_deps }}"
        update_cache: true

    - name: install | import RPM GPG key
      rpm_key:
        key: https://www.percona.com/downloads/RPM-GPG-KEY-percona

    - name: install | set repo
      yum:
        name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm

    - name: install | enable pxc repo
      shell: "percona-release setup pxc{{ percona_pxc_version | replace('.', '') }} -y"
      when: not percona_arbiter_installed

    - name: install | percona xtradb cluster
      dnf:
        name: percona-xtradb-cluster
      when: not percona_arbiter

  when:
    - installed is defined
    - not installed
    - percona_arbiter_installed is defined
    - not percona_arbiter_installed

- name: install | ensure mysql.service.d in systemd directory exists
  file:
    path: /etc/systemd/system/mysql.service.d/
    state: directory
    owner: root
    group: root
    mode: 0755
  when: not percona_arbiter

- name: install | template mysql override file
  template:
    src: mysql.j2
    dest: /etc/systemd/system/mysql.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  when: not percona_arbiter
  register: override_mysql

- name: install | reload daemons when a service file changed
  systemd:
    daemon_reload: true
  when:
    - override_mysql is defined
    - override_mysql.changed
