---
# include distribution-specific variables
- name: Load distro-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

# these reset tasks is meant for development, thus commented out by design
# - include_tasks: reset.yml

# tasks are required. Do not skip it
- include_tasks: assert.yml

# tasks is required. Do not skip it
- include_tasks: ip.yml
  when: percona_cluster.enabled

- include_tasks: install.yml

- include_tasks: root.yml
  when: not percona_arbiter

- include_tasks: certs.yml
  when: percona_host_count != '1'

- include_tasks: config.yml

- include_tasks: cluster.yml
  when: percona_cluster.enabled

- include_tasks: scale.yml
  when: percona_cluster.enabled

- include_tasks: arbiter.yml
  when: percona_arbiter

- include_tasks: backup.yml
  when: percona_backup.enabled

- include_tasks: databases.yml
  when: percona_databases | length > 0

- include_tasks: users.yml
  when: percona_users | length > 0

- include_tasks: pmm.yml
  when:
    - percona_pmm.enabled
    - not percona_arbiter
